spring:
# DataSource
  datasource:
    url: jdbc:mysql://localhost/book_application
    username: user
    password: user
    driver-class-name: com.mysql.jdbc.Driver
# JPA
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
# Thymeleaf
  thymeleaf:
    cache: false